
notoFonts =  ['Noto Sans Canadian Aboriginal', 'Noto Sans Devanagari UI', 'Noto Sans Gurmukhi', 'Noto Sans Tamil', 'Noto Sans Devanagari',
              'Noto Sans Display', 'Noto Sans Arabic', 'Noto Sans Canadian Aboriginal', 'Noto Serif Bengali', 'Noto Sans Bengali', 'Noto Sans Malayalam',
              'Noto Sans Canadian Aboriginal', 'Noto Sans Gurmukhi', 'Noto Sans Hebrew', 'Noto Sans Lepcha', 'Noto Sans Kannada', 'Noto Sans Thaana',
              'Noto Serif Devanagari', 'Noto Sans Myanmar', 'Noto Sans Ogham', 'Noto Serif Tamil', 'Noto Sans Devanagari', 'Noto Sans Devanagari',
              'Noto Sans Thai', 'Noto Sans Canadian Aboriginal', 'Noto Serif Dogra', 'Noto Sans Tamil', 'Noto Serif Bengali', 'Noto Sans Display',
              'Noto Sans Thai UI', 'Noto Sans Devanagari UI', 'Noto Sans Buginese', 'Noto Sans Devanagari UI', 'Noto Sans Tai Le', 'Noto Sans Devanagari',
              'Noto Sans Devanagari UI', 'Noto Sans Anatolian Hieroglyphs', 'Noto Naskh Arabic', 'Noto Serif', 'Noto Sans Kayah Li', 'Noto Serif Khmer',
              'Noto Sans Tai Tham', 'Noto Sans Display', 'Noto Sans Symbols', 'Noto Sans Tifinagh', 'Noto Sans Psalter Pahlavi', 'Noto Serif Sinhala',
              'Noto Serif Malayalam', 'Noto Sans Thaana', 'Noto Serif Tamil', 'Noto Music', 'Noto Serif Malayalam', 'Noto Sans Gurmukhi UI',
              'Noto Sans Sinhala', 'Noto Sans Cherokee', 'Noto Sans Mongolian', 'Noto Serif Kannada', 'Noto Sans Sinhala', 'Noto Sans Old South Arabian',
              'Noto Serif Gurmukhi', 'Noto Sans Brahmi', 'Noto Sans Bengali UI', 'Noto Serif Lao', 'Noto Sans Adlam', 'Noto Sans Tamil Supplement',
              'Noto Sans Chakma', 'Noto Sans Tirhuta', 'Noto Sans Malayalam', 'Noto Sans Canadian Aboriginal', 'Noto Serif Gujarati', 'Noto Sans Cherokee',
              'Noto Sans Tamil UI', 'Noto Serif Sinhala', 'Noto Sans Thai UI', 'Noto Sans Javanese', 'Noto Serif Thai', 'Noto Sans Telugu',
              'Noto Sans Syriac', 'Noto Sans Lao UI', 'Noto Serif Lao', 'Noto Sans Multani', 'Noto Sans Myanmar UI', 'Noto Sans Shavian',
              'Noto Sans Telugu UI', 'Noto Serif Georgian', 'Noto Serif Kannada', 'Noto Sans Oriya UI', 'Noto Sans Malayalam UI', 'Noto Serif Georgian',
              'Noto Serif Georgian', 'Noto Sans Mandaic', 'Noto Sans Bengali', 'Noto Sans Telugu UI', 'Noto Sans Sinhala UI', 'Noto Sans Kharoshthi',
              'Noto Serif Georgian', 'Noto Sans Tamil', 'Noto Sans Old Sogdian', 'Noto Serif Gujarati', 'Noto Serif Gujarati', 'Noto Sans Myanmar',
              'Noto Sans Sinhala UI', 'Noto Sans Old Persian', 'Noto Sans Tamil UI', 'Noto Sans Old Hungarian', 'Noto Sans Cham', 'Noto Sans Telugu UI',
              'Noto Sans Gurmukhi', 'Noto Serif Gurmukhi', 'Noto Sans Arabic UI', 'Noto Serif Lao', 'Noto Serif Bengali', 'Noto Sans Bhaiksuki',
              'Noto Sans Thai UI', 'Noto Sans Tamil UI', 'Noto Sans Deseret', 'Noto Sans Runic', 'Noto Serif Kannada', 'Noto Serif Devanagari',
              'Noto Sans Gurmukhi UI', 'Noto Sans Hebrew', 'Noto Sans Khojki', 'Noto Sans Buhid', 'Noto Sans Armenian', 'Noto Serif Telugu',
              'Noto Sans Devanagari UI', 'Noto Serif Telugu', 'Noto Sans Malayalam UI', 'Noto Sans Sinhala', 'Noto Serif Display', 'Noto Sans Malayalam UI',
              'Noto Serif Tamil Slanted', 'Noto Sans Tai Viet', 'Noto Sans Kannada', 'Noto Sans Hanifi Rohingya', 'Noto Serif Tibetan', 'Noto Sans Khmer UI',
              'Noto Sans', 'Noto Sans', 'Noto Sans Inscriptional Parthian', 'Noto Serif Khmer', 'Noto Sans Ethiopic', 'Noto Sans Mayan Numerals',
              'Noto Sans Lao UI', 'Noto Sans Georgian', 'Noto Sans Hatran', 'Noto Serif Sinhala', 'Noto Kufi Arabic', 'Noto Sans Telugu UI',
              'Noto Sans Bengali UI', 'Noto Sans Tagalog', 'Noto Sans Georgian', 'Noto Serif Tamil Slanted', 'Noto Sans Malayalam', 'Noto Sans Syriac',
              'Noto Serif Myanmar', 'Noto Sans Osage', 'Noto Sans Gurmukhi UI', 'Noto Sans Thai', 'Noto Sans Tamil', 'Noto Sans Batak',
              'Noto Sans Glagolitic', 'Noto Sans Malayalam', 'Noto Sans Khmer UI', 'Noto Serif Myanmar', 'Noto Sans Myanmar UI', 'Noto Sans Old North Arabian',
              'Noto Sans Cham', 'Noto Sans Oriya', 'Noto Sans Khmer', 'Noto Serif Gurmukhi', 'Noto Sans Thai', 'Noto Sans Georgian',
              'Noto Serif Malayalam', 'Noto Sans Mahajani', 'Noto Sans Telugu', 'Noto Sans', 'Noto Serif', 'Noto Serif Tamil Slanted',
              'Noto Sans Linear A', 'Noto Sans Linear B', 'Noto Sans Bengali UI', 'Noto Serif Thai', 'Noto Sans Cham', 'Noto Sans Gothic',
              'Noto Sans Lydian', 'Noto Serif Tibetan', 'Noto Serif Gujarati', 'Noto Sans Tibetan', 'Noto Sans Siddham', 'Noto Sans Mono',
              'Noto Sans Myanmar UI', 'Noto Sans Ol Chiki', 'Noto Sans Display', 'Noto Sans Georgian', 'Noto Sans Tamil UI', 'Noto Sans Mono',
              'Noto Sans Mono', 'Noto Serif', 'Noto Serif Bengali', 'Noto Sans Arabic', 'Noto Sans Modi', 'Noto Sans Lao UI',
              'Noto Serif Tibetan', 'Noto Sans Symbols', 'Noto Sans Sora Sompeng', 'Noto Sans Myanmar', 'Noto Sans Khmer UI', 'Noto Sans Meetei Mayek',
              'Noto Sans Gujarati UI', 'Noto Sans Cypriot', 'Noto Serif Thai', 'Noto Serif Tamil', 'Noto Serif Gujarati', 'Noto Sans Miao',
              'Noto Sans Gurmukhi UI', 'Noto Sans Pahawh Hmong', 'Noto Sans Ugaritic', 'Noto Sans Lao', 'Noto Sans Marchen', 'Noto Sans Cherokee',
              'Noto Serif Thai', 'Noto Sans Arabic', 'Noto Sans Mro', 'Noto Sans Thai', 'Noto Sans PhagsPa', 'Noto Sans Imperial Aramaic',
              'Noto Sans Symbols', 'Noto Sans Tamil UI', 'Noto Sans Telugu', 'Noto Sans Khmer UI', 'Noto Serif Kannada', 'Noto Sans Lao',
              'Noto Sans Kannada UI', 'Noto Sans Bengali', 'Noto Sans Adlam Unjoined', 'Noto Serif Lao', 'Noto Sans Telugu', 'Noto Sans Arabic',
              'Noto Serif Hebrew', 'Noto Serif Gurmukhi', 'Noto Sans Lao', 'Noto Sans Meroitic', 'Noto Serif Khmer', 'Noto Sans Display',
              'Noto Sans Khmer', 'Noto Sans Bengali', 'Noto Sans Gujarati', 'Noto Sans Malayalam UI', 'Noto Sans Cham', 'Noto Sans Malayalam UI',
              'Noto Sans Lao', 'Noto Sans Egyptian Hieroglyphs', 'Noto Sans Kannada UI', 'Noto Sans Bassa Vah', 'Noto Serif Hebrew', 'Noto Sans Bengali UI',
              'Noto Sans Manichaean', 'Noto Sans Ethiopic', 'Noto Sans Indic Siyaq Numbers', 'Noto Sans Armenian', 'Noto Sans', 'Noto Sans Grantha',
              'Noto Sans Arabic UI', 'Noto Sans Kannada UI', 'Noto Serif Ethiopic', 'Noto Sans Armenian', 'Noto Serif Balinese', 'Noto Sans Duployan',
              'Noto Sans Thaana', 'Noto Serif Ethiopic', 'Noto Serif Malayalam', 'Noto Sans Symbols', 'Noto Serif Myanmar', 'Noto Sans Arabic UI',
              'Noto Sans Bengali UI', 'Noto Sans Old Italic', 'Noto Sans Arabic', 'Noto Serif Armenian', 'Noto Sans Bengali', 'Noto Serif Ethiopic',
              'Noto Sans Lisu', 'Noto Sans Thai', 'Noto Sans Khmer', 'Noto Sans Thaana', 'Noto Sans Kaithi', 'Noto Serif Hebrew',
              'Noto Sans Math', 'Noto Naskh Arabic UI', 'Noto Sans Tagbanwa', 'Noto Sans Arabic UI', 'Noto Serif Armenian', 'Noto Sans Arabic UI',
              'Noto Serif Armenian', 'Noto Sans Myanmar', 'Noto Serif Ethiopic', 'Noto Sans Vai', 'Noto Serif Sinhala', 'Noto Serif Armenian',
              'Noto Sans NKo', 'Noto Serif Devanagari', 'Noto Sans Lao', 'Noto Sans New Tai Lue', 'Noto Serif Georgian', 'Noto Sans Syloti Nagri',
              'Noto Sans Ethiopic', 'Noto Serif Malayalam', 'Noto Serif Devanagari', 'Noto Sans Sinhala UI', 'Noto Serif Tibetan', 'Noto Sans Symbols',
              'Noto Serif Lao', 'Noto Sans', 'Noto Serif Khmer', 'Noto Sans Samaritan', 'Noto Sans Thaana', 'Noto Sans Gurmukhi UI',
              'Noto Serif Tamil Slanted', 'Noto Sans Newa', 'Noto Serif Telugu', 'Noto Sans Carian', 'Noto Kufi Arabic', 'Noto Sans Bamum',
              'Noto Serif Thai', 'Noto Sans Takri', 'Noto Serif Tamil Slanted', 'Noto Sans Nabataean', 'Noto Sans Hebrew', 'Noto Serif',
              'Noto Sans Avestan', 'Noto Serif Myanmar', 'Noto Sans Cuneiform', 'Noto Serif Hebrew', 'Noto Sans Kannada', 'Noto Sans Khmer UI',
              'Noto Sans Armenian', 'Noto Sans Elbasan', 'Noto Sans Armenian', 'Noto Sans Old Turkic', 'Noto Sans Ethiopic', 'Noto Color Emoji',
              'Noto Sans Limbu', 'Noto Serif Tangut', 'Noto Mono', 'Noto Sans Myanmar UI', 'Noto Sans Tamil', 'Noto Sans Sharada',
              'Noto Serif Myanmar', 'Noto Sans Hebrew', 'Noto Sans Osmanya', 'Noto Sans Sinhala UI', 'Noto Sans Sinhala', 'Noto Serif Hebrew',
              'Noto Serif Display', 'Noto Sans Palmyrene', 'Noto Serif Ahom', 'Noto Serif Kannada', 'Noto Sans Lycian', 'Noto Sans Yi',
              'Noto Sans Telugu UI', 'Noto Kufi Arabic', 'Noto Sans Caucasian Albanian', 'Noto Serif', 'Noto Sans Mono', 'Noto Sans Kannada UI',
              'Noto Sans Georgian', 'Noto Sans Pau Cin Hau', 'Noto Sans Saurashtra', 'Noto Sans Khmer', 'Noto Sans Old Permic', 'Noto Sans Sinhala UI',
              'Noto Serif Armenian', 'Noto Sans Lao UI', 'Noto Sans Warang Citi', 'Noto Sans Myanmar UI', 'Noto Sans Syriac', 'Noto Serif Sinhala',
              'Noto Serif Ethiopic', 'Noto Sans Telugu', 'Noto Sans Thai UI', 'Noto Sans Coptic', 'Noto Sans Gurmukhi', 'Noto Sans Rejang',
              'Noto Serif Bengali', 'Noto Sans Gurmukhi', 'Noto Sans Cherokee', 'Noto Sans Devanagari', 'Noto Sans Symbols2', 'Noto Sans Malayalam',
              'Noto Serif Devanagari', 'Noto Serif Khmer', 'Noto Sans Mono', 'Noto Serif Display', 'Noto Sans Thai UI', 'Noto Serif Display',
              'Noto Serif Telugu', 'Noto Sans Kannada UI', 'Noto Serif Tamil', 'Noto Nastaliq Urdu', 'Noto Sans Ethiopic', 'Noto Sans Cham',
              'Noto Serif Gurmukhi', 'Noto Serif Tibetan', 'Noto Sans Kannada', 'Noto Serif Telugu', 'Noto Sans Lao UI', 'Noto Sans Kannada',
              'Noto Sans Hebrew', 'Noto Sans Hanunoo', 'Noto Sans Inscriptional Pahlavi', 'Noto Sans Khmer', 'Noto Sans Phoenician', 'Noto Sans Sundanese',
              'Noto Serif Tamil', 'Noto Sans Myanmar', 'Noto Sans Khudawadi', 'Noto Serif Display', 'Noto Sans Cherokee', 'Noto Sans Mende Kikakui', 'Noto Sans Sinhala']

